/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ng2-adsense';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from '@angular/core/src/change_detection/change_detection';
import * as import4 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/render/api';
import * as import7 from '@angular/core/src/metadata/view';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/linker/component_factory';
class AdsenseModuleInjector extends import0.NgModuleInjector<import1.AdsenseModule> {
  _AdsenseModule_0:import1.AdsenseModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.AdsenseModule {
    this._AdsenseModule_0 = new import1.AdsenseModule();
    return this._AdsenseModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AdsenseModule)) { return this._AdsenseModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AdsenseModuleNgFactory:import0.NgModuleFactory<import1.AdsenseModule> = new import0.NgModuleFactory(AdsenseModuleInjector,import1.AdsenseModule);
export class Wrapper_AdsenseComponent {
  /*private*/ _eventHandler:Function;
  context:import1.AdsenseComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor() {
    this._changed = false;
    this.context = new import1.AdsenseComponent();
    this._expr_0 = import3.UNINITIALIZED;
    this._expr_1 = import3.UNINITIALIZED;
    this._expr_2 = import3.UNINITIALIZED;
    this._expr_3 = import3.UNINITIALIZED;
  }
  ngOnDetach(view:import4.AppView<any>,componentView:import4.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_adClient(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import5.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.adClient = currValue;
      this._expr_0 = currValue;
    }
  }
  check_adSlot(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import5.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.adSlot = currValue;
      this._expr_1 = currValue;
    }
  }
  check_adFormat(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import5.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.adFormat = currValue;
      this._expr_2 = currValue;
    }
  }
  check_adRegion(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import5.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.adRegion = currValue;
      this._expr_3 = currValue;
    }
  }
  ngDoCheck(view:import4.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import4.AppView<any>,componentView:import4.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import4.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AdsenseComponent_Host:import6.RenderComponentType = import5.createRenderComponentType('',0,import7.ViewEncapsulation.None,([] as any[]),{});
class View_AdsenseComponent_Host0 extends import4.AppView<any> {
  _el_0:any;
  compView_0:import4.AppView<import1.AdsenseComponent>;
  _AdsenseComponent_0_3:Wrapper_AdsenseComponent;
  constructor(viewUtils:import5.ViewUtils,parentView:import4.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AdsenseComponent_Host0,renderType_AdsenseComponent_Host,import8.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import3.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'ng2-adsense',import5.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AdsenseComponent0(this.viewUtils,this,0,this._el_0);
    this._AdsenseComponent_0_3 = new Wrapper_AdsenseComponent();
    this.compView_0.create(this._AdsenseComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._AdsenseComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.AdsenseComponent) && (0 === requestNodeIndex))) { return this._AdsenseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AdsenseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AdsenseComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AdsenseComponentNgFactory:import9.ComponentFactory<import1.AdsenseComponent> = new import9.ComponentFactory<import1.AdsenseComponent>('ng2-adsense',View_AdsenseComponent_Host0,import1.AdsenseComponent);
const styles_AdsenseComponent:any[] = ([] as any[]);
var renderType_AdsenseComponent:import6.RenderComponentType = import5.createRenderComponentType('',0,import7.ViewEncapsulation.None,styles_AdsenseComponent,{});
export class View_AdsenseComponent0 extends import4.AppView<import1.AdsenseComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import5.ViewUtils,parentView:import4.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AdsenseComponent0,renderType_AdsenseComponent,import8.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import3.ChangeDetectorStatus.CheckAlways);
    this._expr_7 = import3.UNINITIALIZED;
    this._expr_8 = import3.UNINITIALIZED;
    this._expr_9 = import3.UNINITIALIZED;
    this._expr_10 = import3.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_1 = import5.createRenderElement(this.renderer,parentRenderNode,'div',new import5.InlineArray2(2,'style','padding-bottom:8px;'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import5.createRenderElement(this.renderer,this._el_1,'ins',new import5.InlineArray4(4,'class','adsbygoogle','style','display:block;'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7:any = this.context.adClient;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementAttribute(this._el_3,'data-ad-client',((currVal_7 == null)? (null as any): currVal_7.toString()));
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.adSlot;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementAttribute(this._el_3,'data-ad-slot',((currVal_8 == null)? (null as any): currVal_8.toString()));
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.context.adFormat;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementAttribute(this._el_3,'data-ad-format',((currVal_9 == null)? (null as any): currVal_9.toString()));
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.adRegion;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementAttribute(this._el_3,'data-ad-region',((currVal_10 == null)? (null as any): currVal_10.toString()));
      this._expr_10 = currVal_10;
    }
  }
}